image: scrapinghub

script:
  - build_docker_image
  - push_docker_image

notify:
  slack:
    webhook_url: '$$SLACK_WEBHOOK_URL'
    channel: '#builds'
    on_started: true
    on_success: true
    on_failure: true
