image: bradrydzewski/python:2.7-scrapinghub

script:
  - git restore-mtime

publish:
  docker:
    docker_host: $DOCKER_HOST
    image_name: i.scrapinghub.com/slackbridge/$CI_BRANCH
    keep_build: true

notify:
  slack:
    webhook_url: '$$SLACK_WEBHOOK_URL'
    channel: '#builds'
    on_started: true
    on_success: true
    on_failure: true
